# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a54be87aa2f2503cad135b684007790c4c3cb6a3b39006cd70ead842c6380343a5fe08187b0319627d09ba4954c4e21d1030b497f0cce37647d78741479a6ae4

test:
  secret_key_base: ded2dd8030a15f55cfeafc17ab7c22e35c386c3ca567a9ba4498c716996ec11d8c4dbfa06347573a0aeecb23b1bcf21e93656ac4408e2826e755c652f5334420

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
